//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPayment
    {
        public int PaymentID { get; set; }
        public Nullable<int> AdditionID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<bool> AccountStatus { get; set; }
        public Nullable<int> TableID { get; set; }
    
        public virtual Addition Addition { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Table Table { get; set; }
    }
}
