//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Addition()
        {
            this.AccountPayments = new HashSet<AccountPayment>();
        }
    
        public int AdditionID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<System.DateTime> AdditionDate { get; set; }
        public string ServiceType { get; set; }
        public Nullable<int> PaymentCode { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPayment> AccountPayments { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Table Table { get; set; }
    }
}
