//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string ExpenseName { get; set; }
        public Nullable<decimal> ExpensePrice { get; set; }
        public string ExpenseType { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
