//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        public int OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<int> ProductPiece { get; set; }
        public string OrderNote { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual ProductOrder ProductOrders1 { get; set; }
        public virtual ProductOrder ProductOrder1 { get; set; }
        public virtual Table Table { get; set; }
    }
}
