//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public string ReservationNote { get; set; }
        public Nullable<int> PersonCount { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Phone { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Table Table { get; set; }
    }
}
